### ISSUE TITLE
kotlin2js output one file for every kotlin file.

### ISSUE THREAD

**Issue by jiqimaogou** [SebastianAigner/advent-of-code-2020#1]
hello, do you plan to output one file for every kotlin file.
for now, all kotin files is bundle in to one js file.
but at sometimes, like chrome extension develop, it has some structure, so can you please output one file for every kotlin file.
and let webpack do more build task.

**Comment by SebastianAigner** [comment]
This personal project only targets Kotlin/JVM. For inquiries regarding Kotlin/JS, please consider submitting an issue via kotl.in/issue . Thanks and happy holidays.
